/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ficha01.view;

import ficha01.controller.Controller;
import ficha01.model.Usuario;

import javax.swing.JOptionPane;

/**
 *
 * @author Mutisse
 */
public class TelaRegistoAdmin extends javax.swing.JFrame {

    /**
     * Creates new form RegistoUsuario
     */
    public TelaRegistoAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pfSenha2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtApelido = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnRegistar1 = new javax.swing.JButton();
        btnLimpar1 = new javax.swing.JButton();
        rb_Masculino = new javax.swing.JRadioButton();
        rb_Femenino = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCsenha = new javax.swing.JCheckBox();
        pfSenhaC = new javax.swing.JPasswordField();
        pfSenha = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pfSenha2.setBackground(new java.awt.Color(204, 204, 204));
        pfSenha2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Usuários");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pfSenha2.add(jLabel1);
        jLabel1.setBounds(10, 20, 340, 40);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Genero:");
        pfSenha2.add(jLabel2);
        jLabel2.setBounds(40, 300, 70, 30);

        txtApelido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApelidoActionPerformed(evt);
            }
        });
        pfSenha2.add(txtApelido);
        txtApelido.setBounds(270, 140, 220, 28);

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUser.setToolTipText("Introduza um email");
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtUserMouseExited(evt);
            }
        });
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        pfSenha2.add(txtUser);
        txtUser.setBounds(30, 230, 210, 28);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Senha:");
        pfSenha2.add(jLabel5);
        jLabel5.setBounds(270, 200, 100, 22);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Confirmar");
        pfSenha2.add(jLabel6);
        jLabel6.setBounds(410, 200, 110, 22);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("email");
        pfSenha2.add(jLabel7);
        jLabel7.setBounds(30, 200, 90, 20);

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pfSenha2.add(txtNome);
        txtNome.setBounds(30, 140, 210, 28);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/user.png"))); // NOI18N
        pfSenha2.add(jLabel8);
        jLabel8.setBounds(410, 30, 100, 100);

        btnRegistar1.setBackground(new java.awt.Color(204, 255, 255));
        btnRegistar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/atualiz.png"))); // NOI18N
        btnRegistar1.setText("Registar");
        btnRegistar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistar1ActionPerformed(evt);
            }
        });
        pfSenha2.add(btnRegistar1);
        btnRegistar1.setBounds(410, 330, 140, 29);

        btnLimpar1.setBackground(new java.awt.Color(204, 255, 255));
        btnLimpar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/clean.png"))); // NOI18N
        btnLimpar1.setText("Limpar");
        btnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar1ActionPerformed(evt);
            }
        });
        pfSenha2.add(btnLimpar1);
        btnLimpar1.setBounds(260, 330, 120, 29);

        buttonGroup1.add(rb_Masculino);
        rb_Masculino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Masculino.setText("Masculino");
        pfSenha2.add(rb_Masculino);
        rb_Masculino.setBounds(130, 290, 100, 21);

        buttonGroup1.add(rb_Femenino);
        rb_Femenino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Femenino.setText("Femenino");
        pfSenha2.add(rb_Femenino);
        rb_Femenino.setBounds(130, 320, 100, 21);

        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pfSenha2.add(jLabel9);
        jLabel9.setBounds(30, 280, 220, 80);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nome:");
        pfSenha2.add(jLabel4);
        jLabel4.setBounds(30, 110, 90, 22);

        jCsenha.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jCsenha.setText("Mostrar a Senha ");
        jCsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCsenhaActionPerformed(evt);
            }
        });
        pfSenha2.add(jCsenha);
        jCsenha.setBounds(270, 180, 160, 19);

        pfSenhaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfSenhaCActionPerformed(evt);
            }
        });
        pfSenhaC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pfSenhaCKeyTyped(evt);
            }
        });
        pfSenha2.add(pfSenhaC);
        pfSenhaC.setBounds(410, 230, 110, 30);

        pfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfSenhaActionPerformed(evt);
            }
        });
        pfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pfSenhaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pfSenhaKeyTyped(evt);
            }
        });
        pfSenha2.add(pfSenha);
        pfSenha.setBounds(270, 230, 110, 30);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Apelido:");
        pfSenha2.add(jLabel10);
        jLabel10.setBounds(270, 110, 90, 20);

        getContentPane().add(pfSenha2);
        pfSenha2.setBounds(0, 0, 560, 430);

        setSize(new java.awt.Dimension(573, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApelidoActionPerformed

    private void btnRegistar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistar1ActionPerformed

        // Validação dos campos
        char[] senhaChars = pfSenha.getPassword();
        String senha = new String(senhaChars);
        char[] comfirmsenha = pfSenhaC.getPassword();
        String confirmarSenha = new String(comfirmsenha);

        if (controller.camposNaoPreenchidos(txtNome.getText(), txtApelido.getText(), txtUser.getText(), senha, confirmarSenha)) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos.", "", JOptionPane.ERROR_MESSAGE);
        } else if (!controller.senhaIgualConfirmarSenha(senha, confirmarSenha)) {
            JOptionPane.showMessageDialog(null, "A senha e a confirmação de senha devem ser iguais.", "", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Campos preenchidos corretamente.", "", JOptionPane.PLAIN_MESSAGE);
            this.dispose();
            new TelaLogin().setVisible(true);
        }

    }//GEN-LAST:event_btnRegistar1ActionPerformed

    private void btnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar1ActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btnLimpar1ActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void jCsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCsenhaActionPerformed
        if (jCsenha.isSelected()) {
            pfSenha.setEchoChar((char) 0);
            pfSenhaC.setEchoChar((char) 0);
        } else {
            pfSenhaC.setEchoChar('*');
            pfSenha.setEchoChar('*');

        }
    }//GEN-LAST:event_jCsenhaActionPerformed

    private void txtUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseEntered

    }//GEN-LAST:event_txtUserMouseEntered

    private void txtUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseExited

    }//GEN-LAST:event_txtUserMouseExited

    private void pfSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfSenhaKeyReleased

    }//GEN-LAST:event_pfSenhaKeyReleased

    private void pfSenhaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfSenhaCActionPerformed


    }//GEN-LAST:event_pfSenhaCActionPerformed

    private void pfSenhaCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfSenhaCKeyTyped

        String senha = new String(pfSenha.getPassword());
        if (!controller.validarSenha(senha)) {
            JOptionPane.showMessageDialog(null, "Senha inválida! A senha deve ter entre 6 e 16 caracteres e conter apenas letras e números.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

    }//GEN-LAST:event_pfSenhaCKeyTyped

    private void pfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfSenhaActionPerformed

    private void pfSenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfSenhaKeyTyped

        if (controller.validarEmail(txtUser.getText())) {
        } else {
            JOptionPane.showMessageDialog(null, txtUser.getText() + " não é um e-mail válido.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pfSenhaKeyTyped

    public void LimparCampos() {
        txtNome.setText(null);
        txtApelido.setText(null);
        txtUser.setText(null);
        pfSenhaC.setText(null);
        pfSenha.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistoAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistoAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistoAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistoAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistoAdmin().setVisible(true);
            }
        });
    }
    Controller controller = new Controller();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar1;
    private javax.swing.JButton btnRegistar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCsenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JPanel pfSenha2;
    private javax.swing.JPasswordField pfSenhaC;
    private javax.swing.JRadioButton rb_Femenino;
    private javax.swing.JRadioButton rb_Masculino;
    private javax.swing.JTextField txtApelido;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
