/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ficha01.view;

import ficha01.model.Usuario;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Mutisse
 */
public final class TelaPerfil extends javax.swing.JInternalFrame {

    private Usuario usuario; // Declare a variável usuario aqui

    public Usuario getUsuario() {
        return usuario;
    }

    public JPasswordField getPfSenha() {
        return pfSenha;
    }

    public void setPfSenha(JPasswordField pfSenha) {
        this.pfSenha = pfSenha;
    }

    public JPasswordField getPfSenha1() {
        return pfSenha1;
    }

    public void setPfSenha1(JPasswordField pfSenha1) {
        this.pfSenha1 = pfSenha1;
    }

    public JRadioButton getRb_Femenino() {
        return rb_Femenino;
    }

    public void setRb_Femenino(JRadioButton rb_Femenino) {
        this.rb_Femenino = rb_Femenino;
    }

    public JRadioButton getRb_Masculino() {
        return rb_Masculino;
    }

    public void setRb_Masculino(JRadioButton rb_Masculino) {
        this.rb_Masculino = rb_Masculino;
    }

    public JTextField getTxtApelido() {
        return txtApelido;
    }

    public void setTxtApelido(JTextField txtApelido) {
        this.txtApelido = txtApelido;
    }

    public JTextField getTxtNome() {
        return txtNome;
    }

    public void setTxtNome(JTextField txtNome) {
        this.txtNome = txtNome;
    }

    public JTextField getTxtemail() {
        return txtemail;
    }

    public void setTxtemail(JTextField txtemail) {
        this.txtemail = txtemail;
    }

    /**
     * Creates new form NewJInternalFrame
     */
    public TelaPerfil() {
        initComponents();
        txtNome.setEnabled(false);
        txtApelido.setEnabled(false);
        txtemail.setEnabled(false);
        pfSenha.setEnabled(false);
        pfSenha1.setEnabled(false);
        pfSenha.setEchoChar('•');
        pfSenha1.setEchoChar('•');
    }

    void Atualizar() {

    }

    void editAction() {
        if (btneditar.getText().equals("Editar")) {
            btneditar.setText("Atualizar");
            btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/people (4).png")));

            txtNome.setEnabled(true);
            txtApelido.setEnabled(true);
            txtemail.setEnabled(true);
            pfSenha.setEnabled(true);
            pfSenha1.setEnabled(true);

        } else {
            btneditar.setText("Editar");
            btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/lapis.png")));

            txtNome.setEnabled(false);
            txtApelido.setEnabled(false);
            txtemail.setEnabled(false);
            pfSenha.setEnabled(false);
            pfSenha1.setEnabled(false);
            Atualizar();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rb_Masculino = new javax.swing.JRadioButton();
        rb_Femenino = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCsenha = new javax.swing.JCheckBox();
        pfSenha = new javax.swing.JPasswordField();
        pfSenha1 = new javax.swing.JPasswordField();
        btnLimpar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtApelido = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Meu Perfil");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel1);
        jLabel1.setBounds(170, 20, 260, 60);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Genero:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(40, 190, 70, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("email");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(270, 170, 140, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Senha:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 290, 110, 22);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Confirmar ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(220, 290, 120, 22);

        buttonGroup1.add(rb_Masculino);
        rb_Masculino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Masculino.setText("Masculino");
        rb_Masculino.setEnabled(false);
        jPanel3.add(rb_Masculino);
        rb_Masculino.setBounds(130, 180, 100, 21);

        buttonGroup1.add(rb_Femenino);
        rb_Femenino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Femenino.setText("Femenino");
        rb_Femenino.setEnabled(false);
        jPanel3.add(rb_Femenino);
        rb_Femenino.setBounds(130, 210, 100, 21);

        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 170, 210, 80);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nome");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(270, 100, 90, 22);

        jCsenha.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jCsenha.setText("Mostrar a Senha ");
        jCsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCsenhaActionPerformed(evt);
            }
        });
        jPanel3.add(jCsenha);
        jCsenha.setBounds(30, 250, 160, 19);

        pfSenha.setEditable(false);
        pfSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pfSenha.setEnabled(false);
        jPanel3.add(pfSenha);
        pfSenha.setBounds(220, 320, 160, 30);

        pfSenha1.setEditable(false);
        pfSenha1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pfSenha1.setEnabled(false);
        pfSenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfSenha1ActionPerformed(evt);
            }
        });
        jPanel3.add(pfSenha1);
        pfSenha1.setBounds(30, 320, 160, 30);

        btnLimpar.setBackground(new java.awt.Color(204, 255, 255));
        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/clean.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpar);
        btnLimpar.setBounds(260, 370, 130, 29);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Apelido");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(30, 100, 90, 22);

        txtNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });
        jPanel3.add(txtNome);
        txtNome.setBounds(30, 130, 210, 30);

        txtApelido.setEditable(false);
        txtApelido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(txtApelido);
        txtApelido.setBounds(270, 130, 210, 30);

        txtemail.setEditable(false);
        txtemail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel3.add(txtemail);
        txtemail.setBounds(270, 210, 210, 30);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(30, 280, 580, 20);

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/male-icon-11.png"))); // NOI18N
        jPanel3.add(jButton1);
        jButton1.setBounds(500, 110, 110, 140);

        btneditar.setBackground(new java.awt.Color(204, 255, 255));
        btneditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/lapis.png"))); // NOI18N
        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        jPanel3.add(btneditar);
        btneditar.setBounds(420, 370, 160, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 620, 420);

        setBounds(0, 0, 639, 459);
    }// </editor-fold>//GEN-END:initComponents

    private void jCsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCsenhaActionPerformed
        if (jCsenha.isSelected()) {
            pfSenha1.setEchoChar((char) 0);
            pfSenha.setEchoChar((char) 0);
        } else {
            pfSenha.setEchoChar('•');
            pfSenha1.setEchoChar('•');

        }
    }//GEN-LAST:event_jCsenhaActionPerformed
    public void LimparCampos() {
        txtNome.setText(null);
        txtApelido.setText(null);
        txtemail.setText(null);
        pfSenha.setText(null);
        pfSenha1.setText(null);
        buttonGroup1.clearSelection();
    }
    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        LimparCampos();


    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed

    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        editAction();
    }//GEN-LAST:event_btneditarActionPerformed

    private void pfSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfSenha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfSenha1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btneditar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCsenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JPasswordField pfSenha1;
    private javax.swing.JRadioButton rb_Femenino;
    private javax.swing.JRadioButton rb_Masculino;
    private javax.swing.JTextField txtApelido;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
