/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ficha01.view;

import ficha01.controller.controllerDivida;
import ficha01.model.Dao.DividasDao;
import ficha01.model.Divida;
import java.awt.Color;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mutisse
 */
public final class TelaPagamento extends javax.swing.JInternalFrame {

    Date data = new Date();
    DateFormat dtHora = DateFormat.getDateTimeInstance();
    controllerDivida controllerDividas = new controllerDivida();
    DividasDao dividasDao = new DividasDao();
    Divida dividasModel = new Divida();

    /**
     * Creates new form TelaPagmmentos
     */
    public TelaPagamento() {
        initComponents();
        linhas = new Object[][]{};
        sdf = new SimpleDateFormat("dd MMMM yyyy");
        preencherTabela();
        lbl_Atual.setText(dtHora.format(data));
        jTabbedPane1.setSelectedIndex(0);

    }

    public void setCampos() {
        try {
            int setar = jTablePagamentos.getSelectedRow();
            lbl_id.setText(jTablePagamentos.getModel().getValueAt(setar, 0).toString());
            // Obtém o nome completo (nome + apelido)
            lbl_nomeCompleto.setText(jTablePagamentos.getModel().getValueAt(setar, 1).toString());
            // Verifica o gênero e seleciona o RadioButton apropriado
            lbl_emprstado.setText(jTablePagamentos.getModel().getValueAt(setar, 2).toString());
            // Preenche outros campos conforme necessário
            lbl_Apagar.setText(jTablePagamentos.getModel().getValueAt(setar, 3).toString());
            lbl_ValorRemanescente.setText(jTablePagamentos.getModel().getValueAt(setar, 4).toString());

            if (jTablePagamentos.getModel().getValueAt(setar, 5).toString().equalsIgnoreCase("Parcial")) {
                txtEstado.setForeground(Color.BLACK);
                txtEstado.setText(jTablePagamentos.getModel().getValueAt(setar, 5).toString());
            } else {
                txtEstado.setForeground(Color.RED);
                txtEstado.setText(jTablePagamentos.getModel().getValueAt(setar, 5).toString());
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e + " Erro!! Campo Selecionado está vazio", "Notificação", JOptionPane.ERROR);
        }
    }

    void preencherTabela() {
        try {

            DividasDao divida = new DividasDao();
            List<Divida> lista = divida.listarClientesComDividas();
            DefaultTableModel newModelTable = (DefaultTableModel) jTablePagamentos.getModel();
            newModelTable.setRowCount(0);
            for (Divida d : lista) {

                // Verifica se o estado da dívida é "pendente" antes de adicionar à tabela
                //String[] colunas = new String[]{"ID ","Nome Completo","Emprestado", "A Pagar", "Remanescente", "Estado"};
                if (!d.getEstadoDivida().getStatus().equalsIgnoreCase("Liquidada")) {
                    newModelTable.addRow(new Object[]{
                        d.getId_divida(),
                        d.getCliente().getNomeProprio() + " " + d.getCliente().getApelido(),
                        d.getValorDivida(),
                        d.getValorAPagar(),
                        d.getRemanescente(),
                        d.getEstadoDivida().getStatusFormatado() // Aqui está a correção
                    });
                }

            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e.getMessage() + " Erro ao preencher a tabela", "Notificação", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void Pagar() {

    }

    public void Limpar() {
        lbl_nomeCompleto.setText(null);
        lbl_id.setText(null);
        lbl_Apagar.setText(null);
        lbl_emprstado.setText(null);
        txtEstado.setText(null);
        lbl_ValorRemanescente.setText(null);
        spnValor.setValue(0);
    }

    ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        txtPesquisar = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePagamentos = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        lbl_nomeCompleto = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        lbl_Atual = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        lbl_ValorRemanescente = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        spnValor = new javax.swing.JSpinner();
        jLabel63 = new javax.swing.JLabel();
        lbl_Apagar = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        btnRegistar = new javax.swing.JButton();
        txtEstado = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        lbl_emprstado = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel6.setLayout(null);

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyTyped(evt);
            }
        });
        txtPesquisar.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txtPesquisarVetoableChange(evt);
            }
        });
        jPanel6.add(txtPesquisar);
        txtPesquisar.setBounds(10, 140, 190, 30);

        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/supervisor-icon-3 (Copy).png"))); // NOI18N
        jPanel6.add(jLabel68);
        jLabel68.setBounds(400, 10, 190, 170);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/Pesq.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);
        jButton1.setBounds(210, 140, 40, 30);

        jTablePagamentos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIdex){
                return false;
            }
        };
        String[] colunas = new String[]{"ID ","Nome ","Emprestado", "A Pagar", "Remanescente", "Estado"};
        model = new DefaultTableModel(linhas, colunas);
        jTablePagamentos.setModel(model);
        jTablePagamentos.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTablePagamentos.getColumnModel().getColumn(1).setPreferredWidth(115);
        jTablePagamentos.getColumnModel().getColumn(2).setPreferredWidth(60);
        jTablePagamentos.getColumnModel().getColumn(3).setPreferredWidth(60);
        jTablePagamentos.getColumnModel().getColumn(4).setPreferredWidth(60);
        jTablePagamentos.getColumnModel().getColumn(5).setPreferredWidth(60);
        jTablePagamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePagamentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePagamentos);

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(10, 180, 600, 200);

        jTabbedPane1.addTab("Pesquisar", jPanel6);

        jPanel7.setLayout(null);

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(51, 51, 51));
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("Pagamentos");
        jLabel64.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel64.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel64);
        jLabel64.setBounds(130, 30, 320, 60);

        lbl_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 51, 51));
        lbl_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_id.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(lbl_id);
        lbl_id.setBounds(20, 130, 100, 30);

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel65.setText("Nome do Cliente:");
        jPanel7.add(jLabel65);
        jLabel65.setBounds(20, 170, 160, 20);

        lbl_nomeCompleto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nomeCompleto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(lbl_nomeCompleto);
        lbl_nomeCompleto.setBounds(20, 210, 260, 30);

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/loan.png"))); // NOI18N
        jPanel7.add(jLabel59);
        jLabel59.setBounds(490, 10, 120, 100);

        lbl_Atual.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jPanel7.add(lbl_Atual);
        lbl_Atual.setBounds(10, 10, 180, 20);

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel61.setText("  Remanescente:");
        jPanel7.add(jLabel61);
        jLabel61.setBounds(10, 250, 160, 17);

        lbl_ValorRemanescente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_ValorRemanescente.setForeground(new java.awt.Color(255, 51, 51));
        lbl_ValorRemanescente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ValorRemanescente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(lbl_ValorRemanescente);
        lbl_ValorRemanescente.setBounds(20, 280, 130, 30);

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel62.setText("Valor da  Divida:");
        jPanel7.add(jLabel62);
        jLabel62.setBounds(350, 250, 140, 17);

        spnValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spnValor.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 50.0d));
        spnValor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnValorStateChanged(evt);
            }
        });
        spnValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                spnValorMouseReleased(evt);
            }
        });
        spnValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spnValorKeyReleased(evt);
            }
        });
        jPanel7.add(spnValor);
        spnValor.setBounds(350, 280, 140, 30);

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel63.setText("A Pagar:");
        jPanel7.add(jLabel63);
        jLabel63.setBounds(470, 180, 90, 17);

        lbl_Apagar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Apagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Apagar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(lbl_Apagar);
        lbl_Apagar.setBounds(470, 210, 100, 30);

        jButton13.setBackground(new java.awt.Color(204, 255, 255));
        jButton13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/clean.png"))); // NOI18N
        jButton13.setText("Limpar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton13);
        jButton13.setBounds(310, 350, 120, 30);

        btnRegistar.setBackground(new java.awt.Color(204, 255, 255));
        btnRegistar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/paypa.png"))); // NOI18N
        btnRegistar.setText("Pagar");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });
        jPanel7.add(btnRegistar);
        btnRegistar.setBounds(470, 350, 100, 30);

        txtEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(txtEstado);
        txtEstado.setBounds(170, 280, 130, 30);

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel70.setText("Status Da divida");
        jPanel7.add(jLabel70);
        jLabel70.setBounds(170, 250, 140, 20);

        lbl_emprstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_emprstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_emprstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(lbl_emprstado);
        lbl_emprstado.setBounds(350, 210, 100, 30);

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel72.setText("Emprestado:");
        jPanel7.add(jLabel72);
        jLabel72.setBounds(350, 180, 120, 20);

        jTabbedPane1.addTab("Pagamento", jPanel7);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 630, 420);

        setBounds(0, 0, 639, 458);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        Pagar();
        preencherTabela();
        Limpar();
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        Limpar();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void spnValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnValorKeyReleased

    }//GEN-LAST:event_spnValorKeyReleased

    private void spnValorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spnValorMouseReleased

    }//GEN-LAST:event_spnValorMouseReleased

    private void spnValorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnValorStateChanged
        double valor = (double) spnValor.getValue();
        BigDecimal valorAPagar = BigDecimal.valueOf(valor);
//       lbl_ValorRemanescente.setText(dividasModel.calcularRemanescente(valorAPagar).toString());

    }//GEN-LAST:event_spnValorStateChanged

    private void jTablePagamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePagamentosMouseClicked
        setCampos();
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jTablePagamentosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        preencherTabela();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPesquisarVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txtPesquisarVetoableChange

    }//GEN-LAST:event_txtPesquisarVetoableChange

    private void txtPesquisarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyTyped
        if (txtEstado.getText().equals("Não Pago")) {
            btnRegistar.setEnabled(true);
        } else if (txtEstado.getText().equals("Pago")) {
            btnRegistar.setEnabled(false);
        }
    }//GEN-LAST:event_txtPesquisarKeyTyped

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        dividasDao.findData(txtPesquisar.getText(), jTablePagamentos);
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private DefaultTableModel model;
    private final Object[][] linhas;
    private String dataf;
    private final SimpleDateFormat sdf;
    private boolean found = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablePagamentos;
    public javax.swing.JLabel lbl_Apagar;
    public javax.swing.JLabel lbl_Atual;
    public javax.swing.JLabel lbl_ValorRemanescente;
    public javax.swing.JLabel lbl_emprstado;
    public javax.swing.JLabel lbl_id;
    public javax.swing.JLabel lbl_nomeCompleto;
    private javax.swing.JSpinner spnValor;
    public javax.swing.JLabel txtEstado;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
